FROM denoland/deno:alpine-1.28.3

ARG BASE_DIR=/workspace/www/pit-garden-gatekeeper/bonbon

WORKDIR ${BASE_DIR}/

# Caching deno modules
COPY ./src ./src
COPY ./deps.json ./lock.json ./
RUN deno cache --import-map=deps.json --unstable --lock=lock.json src/app.ts \
  && rm lock.json

# Switch to non-root user
RUN chown -R deno:deno ${BASE_DIR}/ \
  && chown -R deno:deno /deno-dir
USER deno

EXPOSE 3000

# Run app
CMD [ \
  "run", \
  "--allow-net", \
  "--import-map=/workspace/www/pit-garden-gatekeeper/bonbon/deps.json", \
  "/workspace/www/pit-garden-gatekeeper/bonbon/src/app.ts" \
  ]